databases:
  # 1. Base de données gratuite
  - name: fastef-db
    plan: free
    region: frankfurt

services:
  # 2. Serveur Backend Laravel (API)
  - type: web
    name: fastef-api
    env: docker
    plan: free
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Fastef
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: fastef-db
          property: connectionString
      # On autorise les requêtes de tous les sous-domaines
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

  # 3. Serveur Frontend Next.js (Interface)
  - type: web
    name: fastef-frontend
    env: node
    plan: free
    region: frankfurt
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        value: https://fastef-api.onrender.com
